# Content Security Policy (CSP)
# See https://content-security-policy.com/ for more information and examples
add_header Content-Security-Policy "default-src 'self';" always;

# HSTS
add_header Strict-Transport-Security "max-age=300; includeSubDomains";
# Preload feature (see https://hstspreload.org/) -> https://hstspreload.org/#deployment-recommendations
add_header Strict-Transport-Security "max-age=604800; includeSubDomains";
add_header Strict-Transport-Security "max-age=2592000; includeSubDomains";
add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload";
